### ISSUE TITLE
Pagina de Documentacion caida

### ISSUE THREAD

**Issue by YouDA61** [josego85/api-geo-paraguay#32]
Estoy queriendo entrar en la documentacion, realmente no se ni como funciona la aplicacion, acabo de encontrarme este repositorio y me pareceria interesante probarla con algo que tengo

**Comment by josego85** [comment]
Hola @YouDA61 

Donde estas queriendo entrar? Por eso que decís que la Documentación esta caída?
Es un API sobre los departamentos, ciudades, distritos y ciudades de Paraguay.

En este [link](https://api-geo.proyectosbeta.net/api/v1/departamentos/-56.987/-25.564) podes probar el API. 
En el readme explico los pasos para que funcione en tu local o estas links de diferentes endpoints para que veas los resultados.

Cualquier duda o consulta, podes preguntar.

Saludos, José

**Comment by YouDA61** [comment]
Me referia en esta parte

Documentación
Access
Oficial site

Envia a la pagina de proyesctos beta y no devuelve nada

**Comment by Centurion95** [comment]
Hola @josego85 tuve la misma observación que  @YouDA61 

A continuación imagenes de referencia:

El link en el README:
![img_1](https://github.com/user-attachments/assets/0ffe634f-c6c2-4aa9-a54e-3c11a7ee8f13)

Lleva a la siguiente web:
![img_2](https://github.com/user-attachments/assets/f663ed46-3b3c-4086-b509-84129e019ef2)


Saludos!

**Comment by josego85** [comment]
@Centurion95 @YouDA61 

Gracias. Estoy viendo de arreglar eso. En una de las actualizaciones del paquete del swagger se rompió algo. 

Gracias a los dos.

**Comment by josego85** [comment]
@Centurion95 @YouDA61 

Esta corregido el problema. Pueden ver la documentation en --> [Docs](https://api-geo.proyectosbeta.net/api-docs/)

Gracias por reportar
